In [32]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [33]:
fake = pd.read_csv(r"C:\Users\K.EEKSHITHASIVA DEVI\Downloads\Fake.csv")

In [34]:
true = pd.read_csv(r"C:\Users\K.EEKSHITHASIVA DEVI\Downloads\True.csv")

In [35]:
true.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [36]:
fake.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [37]:
true['label'] = 1

In [38]:
fake['label'] = 0

In [39]:
true.head()

,title,text,subject,date,label
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",1
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",1
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",1
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",1
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",1

In [40]:
news = pd.concat([fake, true], axis=0)

In [41]:
news.head()

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0

In [42]:
news.tail()

,title,text,subject,date,label
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017",1
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017",1
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017",1
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017",1
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017",1

In [43]:
news.isnull().sum()

title      0
text       0
subject    0
date       0
label      0
dtype: int64

In [44]:
news = news.drop(['title','subject','date'],axis = 1)

In [45]:
news.head()

                                                text  label
0  Donald Trump just couldn t wish all Americans ...      0
1  House Intelligence Committee Chairman Devin Nu...      0
2  On Friday, it was revealed that former Milwauk...      0
3  On Christmas day, Donald Trump announced that ...      0
4  Pope Francis used his annual Christmas Day mes...      0

In [46]:
news = news.sample(frac=1)                #Reshuffling

In [47]:
news.head()

                                                    text  label
6869   It doesn t matter how loudly Fox News protests...      0
5638   Ever since Donald Trump s true character was r...      0
5563   Republicans are desperately trying to convince...      0
18768  Earlier this evening, Le Pen had security auth...      0
559    WASHINGTON (Reuters) - A group of about a doze...      1

In [48]:
news.reset_index(inplace=True)

In [49]:
news.head()

   index                                               text  label
0   6869  It doesn t matter how loudly Fox News protests...      0
1   5638  Ever since Donald Trump s true character was r...      0
2   5563  Republicans are desperately trying to convince...      0
3  18768  Earlier this evening, Le Pen had security auth...      0
4    559  WASHINGTON (Reuters) - A group of about a doze...      1

In [50]:
news.drop(['index'],axis=1,inplace=True)

In [51]:
news.head()

                                                text  label
0  It doesn t matter how loudly Fox News protests...      0
1  Ever since Donald Trump s true character was r...      0
2  Republicans are desperately trying to convince...      0
3  Earlier this evening, Le Pen had security auth...      0
4  WASHINGTON (Reuters) - A group of about a doze...      1

In [52]:
import re       #regular expression

In [53]:
def wordopt(text):
    # Convert into lowercase
    text = text.lower()

    # Remove URLs
    text = re.sub(r'https?://\S+|www\.\S+', '', text)

    # Remove HTML tags
    text = re.sub(r'<.*?>', '', text)

    # Remove punctuation
    text = re.sub(r'[^\w\s]', '', text)

    # Remove digits
    text = re.sub(r'\d', '', text)

    # Remove newline characters
    text = re.sub(r'\n', ' ', text)

    return text

In [54]:
news['text'] = news['text'].apply(wordopt)

In [55]:
news['text']

0        it doesn t matter how loudly fox news protests...
1        ever since donald trump s true character was r...
2        republicans are desperately trying to convince...
3        earlier this evening le pen had security autho...
4        washington reuters  a group of about a dozen u...
                               ...
44893    donald trump has again made a huge mistake whi...
44894    it seems the trump administration will stop at...
44895    amateur president donald trump is donating his...
44896    presidentelect donald trump is currently tryin...
44897    zurich reuters  around  people were injured on...
Name: text, Length: 44898, dtype: object

In [56]:
x = news['text']
y = news['label']

In [57]:
x

0        it doesn t matter how loudly fox news protests...
1        ever since donald trump s true character was r...
2        republicans are desperately trying to convince...
3        earlier this evening le pen had security autho...
4        washington reuters  a group of about a dozen u...
                               ...
44893    donald trump has again made a huge mistake whi...
44894    it seems the trump administration will stop at...
44895    amateur president donald trump is donating his...
44896    presidentelect donald trump is currently tryin...
44897    zurich reuters  around  people were injured on...
Name: text, Length: 44898, dtype: object

In [58]:
y

0        0
1        0
2        0
3        0
4        1
        ..
44893    0
44894    0
44895    0
44896    0
44897    1
Name: label, Length: 44898, dtype: int64

In [59]:
from sklearn.model_selection import train_test_split

In [60]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)

In [61]:
x_train.shape

(31428,)

In [62]:
x_test.shape

(13470,)

In [63]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [64]:
vectorization = TfidfVectorizer()

In [65]:
xv_train = vectorization.fit_transform(x_train)

In [66]:
xv_test = vectorization.transform(x_test)

In [67]:
xv_train

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 6471879 stored elements and shape (31428, 175666)>

In [68]:
xv_test

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2709562 stored elements and shape (13470, 175666)>

### Logistic Regression

In [69]:
from sklearn.linear_model import LogisticRegression

In [70]:
LR = LogisticRegression()

In [71]:
LR.fit(xv_train, y_train)

LogisticRegression()

In [72]:
pred_lr = LR.predict(xv_test)

In [73]:
LR.score(xv_test, y_test)

0.9879732739420936

In [74]:
from sklearn.metrics import classification_report

In [75]:
print(classification_report(y_test,pred_lr))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      7055
           1       0.98      0.99      0.99      6415

    accuracy                           0.99     13470
   macro avg       0.99      0.99      0.99     13470
weighted avg       0.99      0.99      0.99     13470

### Decision Tree Classifier

In [76]:
from sklearn.tree import DecisionTreeClassifier

In [77]:
Dtc = DecisionTreeClassifier()

In [ ]:
Dtc.fit(xv_train, y_train)

In [ ]:
pred_dtc = Dtc.predict(xv_test)

In [ ]:
Dtc.score(xv_test,y_test)

In [ ]:
print(classification_report(y_test,pred_dtc))

### Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rfc = RandomForestClassifier()

In [ ]:
rfc.fit(xv_train,y_train)

In [ ]:
pred_rfc = rfc.predict(xv_test)

In [ ]:
rfc.score(xv_test,y_test)

In [ ]:
print(classification_report(y_test,pred_rfc))

### Gradient Boosting

In [ ]:
from sklearn.ensemble import  GradientBoostingClassifier

In [ ]:
gbc = GradientBoostingClassifier()

In [ ]:
gbc.fit(xv_train,y_train)

In [ ]:
pred_gbc = gbc.predict(xv_test)

In [ ]:
gbc.score(xv_test,y_test)

In [ ]:
print(classification_report(y_test,pred_gbc))

In [ ]:
def output_label(n):
    if n == 0:
        return 'It is a Fake News'
    elif n == 1:
        return 'It is a Genuine News'

In [ ]:
def manual_testing(news):
    testing_news = {"text": [news]}

    new_def_test = pd.DataFrame(testing_news)
    new_def_test["text"] = new_def_test["text"].apply(wordopt)

    new_x_test = new_def_test["text"]
    new_xv_test = vectorization.transform(new_x_test)

    pred_lr = LR.predict(new_xv_test)
    # pred_dtc = dtc.predict(new_xv_test)
    pred_gbc = gbc.predict(new_xv_test)
    pred_rfc = rfc.predict(new_xv_test)

    return "\n\nLR Prediction: {} \tGBC Prediction: {} \tRFC Prediction: {}".format(
        output_label(pred_lr[0]),
        output_label(pred_gbc[0]),
        output_label(pred_rfc[0])
    )

In [ ]:
news_article = str(input())

In [ ]:
manual_testing(news_article)

In [ ]:
news_article = str(input())

In [ ]:
manual_testing(news_article)